// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mq_message.proto

/*
Package mq is a generated protocol buffer package.

It is generated from these files:
	mq_message.proto

It has these top-level messages:
	MQMessage
*/
package postoffice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MQMessage struct {
	Host     int32  `protobuf:"varint,1,opt,name=host" json:"host,omitempty"`
	Actor    string `protobuf:"bytes,2,opt,name=actor" json:"actor,omitempty"`
	Resource string `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Action   string `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Payload  []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *MQMessage) Reset()                    { *m = MQMessage{} }
func (m *MQMessage) String() string            { return proto.CompactTextString(m) }
func (*MQMessage) ProtoMessage()               {}
func (*MQMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MQMessage) GetHost() int32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *MQMessage) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *MQMessage) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *MQMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MQMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*MQMessage)(nil), "mq.MQMessage")
}

func init() { proto.RegisterFile("mq_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2d, 0x8c, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x2d,
	0x54, 0x6a, 0x66, 0xe4, 0xe2, 0xf4, 0x0d, 0xf4, 0x85, 0x88, 0x0b, 0x09, 0x71, 0xb1, 0x64, 0xe4,
	0x17, 0x97, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x89,
	0xc9, 0x25, 0xf9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x14, 0x17,
	0x47, 0x51, 0x6a, 0x71, 0x7e, 0x69, 0x51, 0x72, 0xaa, 0x04, 0x33, 0x58, 0x02, 0xce, 0x17, 0x12,
	0xe3, 0x62, 0x4b, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x01, 0xcb, 0x40, 0x79, 0x42, 0x12,
	0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0x3c, 0x41,
	0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x41, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x44, 0x42,
	0xb3, 0xa4, 0x00, 0x00, 0x00,
}
