// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mq_message.proto

/*
Package postoffice is a generated protocol buffer package.

It is generated from these files:
	mq_message.proto

It has these top-level messages:
	MQMessage
*/
package postoffice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MQMessage struct {
	Caller   []byte `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Matrix   string `protobuf:"bytes,2,opt,name=matrix" json:"matrix,omitempty"`
	Device   string `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
	Resource string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	Action   string `protobuf:"bytes,5,opt,name=action" json:"action,omitempty"`
	Payload  []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Time     int64  `protobuf:"varint,7,opt,name=time" json:"time,omitempty"`
}

func (m *MQMessage) Reset()                    { *m = MQMessage{} }
func (m *MQMessage) String() string            { return proto.CompactTextString(m) }
func (*MQMessage) ProtoMessage()               {}
func (*MQMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MQMessage) GetCaller() []byte {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *MQMessage) GetMatrix() string {
	if m != nil {
		return m.Matrix
	}
	return ""
}

func (m *MQMessage) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *MQMessage) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *MQMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MQMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MQMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*MQMessage)(nil), "postoffice.MQMessage")
}

func init() { proto.RegisterFile("mq_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0x31, 0x8e, 0xc2, 0x30,
	0x10, 0x05, 0x50, 0x79, 0x93, 0x4d, 0x36, 0xa3, 0x2d, 0x90, 0x0b, 0x34, 0xa2, 0x8a, 0xa8, 0x52,
	0xd1, 0x70, 0x8e, 0x14, 0xe4, 0x02, 0xc8, 0x38, 0x13, 0x64, 0x29, 0x66, 0x82, 0x6d, 0x10, 0x1c,
	0x8c, 0xfb, 0xa1, 0xd8, 0x81, 0xce, 0xef, 0x7f, 0x7d, 0x59, 0x03, 0x2b, 0x7b, 0x3d, 0x5a, 0xf2,
	0x5e, 0x9d, 0x69, 0x37, 0x39, 0x0e, 0x2c, 0x61, 0x62, 0x1f, 0x78, 0x18, 0x8c, 0xa6, 0xed, 0x4b,
	0x40, 0xd5, 0x1e, 0xda, 0xd4, 0xcb, 0x35, 0x14, 0x5a, 0x8d, 0x23, 0x39, 0x14, 0xb5, 0x68, 0xfe,
	0xbb, 0x45, 0x73, 0x6e, 0x55, 0x70, 0xe6, 0x81, 0x3f, 0xb5, 0x68, 0xaa, 0x6e, 0xd1, 0x9c, 0xf7,
	0x74, 0x37, 0x9a, 0x30, 0x4b, 0x79, 0x92, 0xdc, 0xc0, 0x9f, 0x23, 0xcf, 0x37, 0xa7, 0x09, 0xf3,
	0xd8, 0x7c, 0x3d, 0x6f, 0x94, 0x0e, 0x86, 0x2f, 0xf8, 0x9b, 0x36, 0x49, 0x12, 0xa1, 0x9c, 0xd4,
	0x73, 0x64, 0xd5, 0x63, 0x11, 0x3f, 0xff, 0x50, 0x4a, 0xc8, 0x83, 0xb1, 0x84, 0x65, 0x2d, 0x9a,
	0xac, 0x8b, 0xef, 0x53, 0x11, 0x4f, 0xd9, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x5e, 0x2e,
	0x74, 0xde, 0x00, 0x00, 0x00,
}
