// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mq_message.proto

/*
Package postoffice is a generated protocol buffer package.

It is generated from these files:
	mq_message.proto

It has these top-level messages:
	Address
	MQMessage
*/
package postoffice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Matrix string `protobuf:"bytes,1,opt,name=matrix" json:"matrix,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Address) GetMatrix() string {
	if m != nil {
		return m.Matrix
	}
	return ""
}

func (m *Address) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type MQMessage struct {
	Source      *Address `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Destination *Address `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	Resource    string   `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Action      string   `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Payload     []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Time        int64    `protobuf:"varint,6,opt,name=time" json:"time,omitempty"`
}

func (m *MQMessage) Reset()                    { *m = MQMessage{} }
func (m *MQMessage) String() string            { return proto.CompactTextString(m) }
func (*MQMessage) ProtoMessage()               {}
func (*MQMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MQMessage) GetSource() *Address {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MQMessage) GetDestination() *Address {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *MQMessage) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *MQMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MQMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MQMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Address)(nil), "postoffice.Address")
	proto.RegisterType((*MQMessage)(nil), "postoffice.MQMessage")
}

func init() { proto.RegisterFile("mq_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x4a, 0xc5, 0x30,
	0x14, 0xc7, 0x89, 0xf7, 0x9a, 0xeb, 0x3d, 0x75, 0x90, 0x23, 0x48, 0x70, 0x2a, 0x9d, 0x0a, 0x42,
	0x07, 0xc5, 0xc1, 0xd1, 0x07, 0xe8, 0x60, 0x5e, 0x40, 0x62, 0x72, 0x2a, 0x01, 0xd3, 0xd4, 0x24,
	0x8a, 0x3e, 0xa6, 0x6f, 0x24, 0x4d, 0xe2, 0xc7, 0x72, 0xb7, 0xfc, 0x0e, 0xff, 0x2f, 0x02, 0x67,
	0xee, 0xf5, 0xd1, 0x51, 0x8c, 0xea, 0x99, 0x86, 0x25, 0xf8, 0xe4, 0x11, 0x16, 0x1f, 0x93, 0x9f,
	0x26, 0xab, 0xa9, 0xbb, 0x83, 0xdd, 0xbd, 0x31, 0x81, 0x62, 0xc4, 0x0b, 0xe0, 0x4e, 0xa5, 0x60,
	0x3f, 0x04, 0x6b, 0x59, 0xbf, 0x97, 0x95, 0xd6, 0xbb, 0xa1, 0x77, 0xab, 0x49, 0x1c, 0x95, 0x7b,
	0xa1, 0xee, 0x8b, 0xc1, 0x7e, 0x7c, 0x18, 0x4b, 0x34, 0x5e, 0x01, 0x8f, 0xfe, 0x2d, 0x68, 0xca,
	0xee, 0xe6, 0xfa, 0x7c, 0xf8, 0x6b, 0x19, 0x6a, 0x85, 0xac, 0x12, 0xbc, 0x85, 0xc6, 0x50, 0x4c,
	0x76, 0x56, 0xc9, 0xfa, 0x39, 0xe7, 0x1e, 0x70, 0xfc, 0xd7, 0xe1, 0x25, 0x9c, 0x04, 0xaa, 0x2d,
	0x9b, 0xbc, 0xe5, 0x97, 0xd7, 0x95, 0x4a, 0xe7, 0xb4, 0x6d, 0x59, 0x59, 0x08, 0x05, 0xec, 0x16,
	0xf5, 0xf9, 0xe2, 0x95, 0x11, 0xc7, 0x2d, 0xeb, 0x4f, 0xe5, 0x0f, 0x22, 0xc2, 0x36, 0x59, 0x47,
	0x82, 0xb7, 0xac, 0xdf, 0xc8, 0xfc, 0x7e, 0xe2, 0xf9, 0x87, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0xb7, 0x78, 0x6c, 0x35, 0x01, 0x00, 0x00,
}
