auth:
  type: mongodb
  url: mongodb://192.168.41.170:30707
matrix:
  zookeeper:
    host: zookeeper.default
    port: 2181
mq:
  type: kafka
  host: kafka.default
  port: 9092
source:
  - type: mqtt
    ssl: false
    port: 1883
    keepAlive: 300
    connectTimeout: 2
    ackTimeout: 20
    timeoutRetries: 3
  - type: websocket
    ssl: false
    port: 8080
    keepAlive: 300
    connectTimeout: 2
    ackTimeout: 20
    timeoutRetries: 3
  - type: coap
    ssl: false
    port: 8080
ssl:
  crt: ./cert/postoffice.crt
  key: ./cert/postoffice.key
