auth:
  type: mongodb
  host: mongodb.default
  port: 30707
zookeeper:
  type: zookeeper
  host: zookeeper.default
  port: 2181
  path: /iotnn
  level: 3
redis:
  host: redis.default
  port: 6379
mq:
  type: kafka
  host: kafka.default
  port: 9092
source:
  ssl:
    crt: ./cert/postoffice.crt
    key: ./cert/postoffice.key
  keepAlive: 300
  connectTimeout: 2
  ackTimeout: 20
  timeoutRetries: 3
  channels:
  - type: mqtt
    ssl: false
    port: 1883
  - type: websocket
    ssl: false
    port: 8080
