auth:
  type: mongodb
  url: mongodb://192.168.41.170:30707
matrix:
  zookeeper:
    host: zookeeper.default
    port: 2181
#    host: 39.106.153.134
#    port: 30181
redis:
  host: redis.default
  port: 6379
mq:
  type: kafka
  host: kafka.default
  port: 9092
#  host: 39.106.153.134
#  port: 30092
influxdb:
  host:
  username:
  password:
source:
  - type: mqtt
    ssl: false
    port: 1883
    keepAlive: 300
    connectTimeout: 2
    ackTimeout: 20
    timeoutRetries: 3
  - type: websocket
    ssl: false
    port: 8080
    keepAlive: 300
    connectTimeout: 2
    ackTimeout: 20
    timeoutRetries: 3
  - type: coap
    ssl: false
    port: 8080
ssl:
  crt: ./cert/postoffice.crt
  key: ./cert/postoffice.key
