manager:
  device.offline:
    - manager_dashboard
  device.online:
    - manager_dashboard
  resource.all:
    - manager_dashboard
  resource.get:
    - manager_dashboard
  resource.list:
    - manager_dashboard
  resource.save:
    - manager_dashboard
  page.all:
    - manager_dashboard
  page.get:
    - manager_dashboard
  page.list:
    - manager_dashboard
  page.save:
    - manager_dashboard
  role.all:
    - manager_dashboard
  menu.all:
    - manager_dashboard
  menu.get:
    - manager_dashboard
  menu.list:
    - manager_dashboard
  menu.save:
    - manager_dashboard
  admin.delete:
    - manager_dashboard
  admin.list:
    - manager_dashboard
  admin.post:
    - manager_dashboard
  admin.put:
    - manager_dashboard
  admin.save:
    - manager_dashboard
  app.set_user:
    - manager_dashboard
  group.all:
    - manager_dashboard
  group.delete:
    - manager_dashboard
  group.list:
    - manager_dashboard
  group.post:
    - manager_dashboard
  group.put:
    - manager_dashboard
  group.save:
    - manager_dashboard
  parameter.get:
    - manager_dashboard
  parameter.save:
    - manager_dashboard
  image.upload:
    - manager_dashboard
  matrix.all:
    - manager_velociraptor
  matrix.delete:
    - manager_velociraptor
  matrix.get:
    - manager_velociraptor
  matrix.list:
    - manager_velociraptor
  matrix.save:
    - manager_velociraptor
  matrix.sync:
    - manager_velociraptor
  dance.apply:
    - manager_velociraptor
  dance.delete:
    - manager_velociraptor
  dance.get:
    - manager_velociraptor
  dance.list:
    - manager_velociraptor
  dance.save:
    - manager_velociraptor
  project.all:
    - manager_velociraptor
  project.delete:
    - manager_velociraptor
  project.get:
    - manager_velociraptor
  project.list:
    - manager_velociraptor
  project.save:
    - manager_velociraptor
  document_type.all:
    - manager_blog
  document_type.delete:
    - manager_blog
  document_type.list:
    - manager_blog
  document_type.save:
    - manager_blog
  document.delete:
    - manager_blog
  document.get:
    - manager_blog
  document.list:
    - manager_blog
  document.save:
    - manager_blog
shop-weixin:
  device.online:
    - plus.reply